version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lmsdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: lms-api
    restart: always
    depends_on:
      - db
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      # DATABASE_URL ichidagi hostni 'db' deb o'zgartiramiz (docker tarmog'ida shu nomda)
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/lmsdb?schema=public"
      NODE_ENV: production
    command: npm run start
    volumes:
      - .:/app
    working_dir: /app

volumes:
  pgdata:
